### ISSUE TITLE
Can't deploy on windows 10 - Missing slashes in identity file location

### ISSUE THREAD

**Issue by nolanzandi** [reactioncommerce/reaction-cli#54] opened 2018-01-17 17:42 UTC
I'm attempting to run the rection-cli deploy command on windows 10. I have four apps that I've tried with. below is also my reaction -v output:

![image](https://user-images.githubusercontent.com/2481116/35057548-224d6d60-fb6a-11e7-8b9d-cccce6322787.png)

Most commands work fine, including app create. But when I deploy any app I get this output:

![image](https://user-images.githubusercontent.com/2481116/35057824-fa5faa56-fb6a-11e7-964d-3ba21076339a.png)

As you can see, it doesn't interpret the location of its own Identity file (that the CLI created itself) properly. It seems to skip all the slashes ( I can confirm that the identity file exists in the location it's trying to reach, if it had properly put in the slashes). It looks like a problem in the ssh.js file, but I couldn't get it working. Any help would be great.

And I did confirm that this works fine on Linux.

**Comment by jshimko** [comment] 2018-01-17 18:47
Can you please run the failing command(s) with debug on?

```
REACTION_CLI_DEBUG=true reaction deploy --app <your-app>
```

**Comment by nolanzandi** [comment] 2018-01-17 19:13
It didn't appear to work. Is it supposed to be an environment variable on the app instead?

![image](https://user-images.githubusercontent.com/2481116/35061841-46e801d2-fb77-11e7-814e-0611db8df839.png)

**Comment by jshimko** [comment] 2018-01-17 20:48
Oh sorry, Windows...

The problem is setting the environment variable.  Windows apparently doesn't support inlining it like that.  Do this instead...

```sh
set REACTION_CLI_DEBUG=true

reaction deploy --app yourapp
```

**Comment by nolanzandi** [comment] 2018-01-17 20:58
![image](https://user-images.githubusercontent.com/2481116/35066635-27423c08-fb86-11e7-9ae2-4f4e3d87e403.png)

**Comment by nolanzandi** [comment] 2018-01-17 20:59
![image](https://user-images.githubusercontent.com/2481116/35066647-321e3c76-fb86-11e7-8b11-e6aa7e5d90da.png)

**Comment by nolanzandi** [comment] 2018-01-17 20:59
![image](https://user-images.githubusercontent.com/2481116/35066666-47356e90-fb86-11e7-9c9a-8f25e0511456.png)

**Comment by jshimko** [comment] 2018-01-18 17:59
Ok, sorry for the wait.  Finally figured out what it was.  As you know, Windows obviously uses a `\` in the directory paths and Mac/Linux uses `/`.  Our CLI was properly accounting for that and generating the correct path to your SSH key with `\`'s in it.  However, git requires a hybrid of the two when defining paths in its config.  

So this (which is a proper Windows absolute path syntax)...
```
C:\Users\myname\something
```
Needs to be this for git to interpret it correctly...
```
C:/Users/myname/something
```

So yeah, a hybrid of Windows/Unix path styles.  How lovely of git to do that for us!

As for the slashes missing in the path in your error, that's because on any non-Windows machine those slashes are used for escaping the next character in a string (which made git not even see them and just concatenate the entire path).  So while git clearly works on Windows, it appears to partially operate as if it's on Linux/Mac.

Good times!  Fix coming shortly in `reaction-cli`.

**Comment by zenweasel** [comment] 2018-01-31 22:05
I tested this on Windows and it was working for me so closing.

**Closed by zenweasel** 2018-01-31 22:05 UTC
