### ISSUE TITLE
`reaction run -p 8080` stalls

### ISSUE THREAD

**Issue by mikeumus** [reactioncommerce/reaction-cli#12] opened 2016-09-25 08:45 UTC
![C9](http://i.imgur.com/OoSRewo.png)

When I run `reaction run -p 8080` in Cloud 9 IDE it stalls the terminal. The `PORT` meteor env var is set. 
However, `meteor run -p 8080` does startup the Reaction Commerce dev server successfully. 

Not sure if this is just a Cloud9 issue. If it is feel free to close it until more protesters arrive but just mainly wanted to report on it for now. Cheers. 

Note*
This is on a Pro C9 account with 2.5gb of RAM:
- https://ide.c9.io/mikeumus/ca-blinds

**Comment by jshimko** [comment] 2016-09-25 18:59
Well first, if you set the `PORT` env var, the `-p` argument is redundant.  They're both doing the same thing, so you can just set the env var and leave off the `-p`.

If that hangs at the point you show in the picture, that's where Meteor is building the app.  That unfortunately always takes a long time on first run.  You have 2.5gb of RAM (which should be enough), but what do you have for CPU?  That initial startup takes a long time on my MacBook Pro (which surely has more CPU power than the virtual machine they give you), so I suspect it's just taking longer than you expected it would.  Then when you stopped it and restarted with Meteor, it had already been partially built and went faster that time.  Not sure what else it could be.  `reaction-cli` is literally just running that same command under the hood.

**Comment by mikeumus** [comment] 2016-09-25 19:12
Every time it will stall with `reaction run -p 8080`, and every time it'll run with `meteor run -p 8080`. 
With the `PORT` env var set, `reaction run` and `meteor run` both run the server on port 3000 still for me. 
I added the link to the C9 Workspace in the original post.

**Comment by jshimko** [comment] 2016-10-15 01:43
I can't reproduce this anywhere else, so I have to assume this is isolated to Cloud 9.  I'm going to close this issue for now, but feel free to reopen it if you feel there's an issue with `reaction-cli` that's responsible for your problem.

**Closed by jshimko** 2016-10-15 01:43 UTC

**Comment by mikeumus** [comment] 2016-10-15 16:51
Alright sounds good. I think it happened again when SSH'ing into a Google Compute Engine server but I'll double check and comment here if so. Cheers.
