### ISSUE TITLE
Error: ENFILE: file table overflow

### ISSUE THREAD

**Issue by casoetan** [reactioncommerce/reaction-cli#11] opened 2016-09-10 20:25 UTC
This is game changing, but I've not had the fun to try it out.

I installed the cli and followed the instructions, but

```sh
=> App running at: http://localhost:3000/
/User/me/meteor/packages/coffeescript/.1.2.4_1.12kaiqb++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/User/me/site/reaction/client/modules/i18n/templates/header'
    at Error (native)
```

Help needed.

**Comment by jshimko** [comment] 2016-09-13 16:28
Pretty sure this is an issue with the Node process monitoring too many open files at once.  The default limits on OSX are quite low.  

See [this issue comment](https://github.com/karma-runner/karma/issues/1979#issuecomment-217994084).  That solution did the trick for me last time I had the issue.

And here's the blog post that the answer originally came from...

http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

Let me know if that solves it for you.

**Comment by jshimko** [comment] 2016-09-28 00:09
@casoetan I think my first response is likely the cause/fix of your issue, so I'm going to close this for now.  If you continue to have the issue after trying what I suggested, feel free to reopen this.  

Thanks!

**Closed by jshimko** 2016-09-28 00:09 UTC
